# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  displayName: 'Get Erlang OTP 22.3'
  inputs:
    targetType: 'inline'
    script: |
      wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
      sudo dpkg -i erlang-solutions_1.0_all.deb
      sudo apt-get update
      sudo apt-get install esl-erlang=1:22.3-1 --yes --allow-downgrades

- script: 'erl -eval ''erlang:display(erlang:system_info(otp_release)), halt().''  -noshell'
  displayName: 'Erlang OTP Version'

- script: 'rebar3 compile'
  displayName: 'Rebar Compile'

- task: DeleteFiles@1
  displayName: 'Delete files from $(Build.SourcesDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
     .git
     Dockerfile
     .gitignore

- task: ArchiveFiles@2
  displayName: 'Archive $(Build.SourcesDirectory)'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: build'
  inputs:
    ArtifactName: build
