name: Erlang CI

on: 
  pull_request:
    branches: 
      - develop

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:21.0.1

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar3 compile
